portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('login', views.index, name='index'),
    path('signupdata', views.signupdata, name='signupdata'),
    path('doctor/<int:id>', views.doctor, name='doctor'),
    path('patient/<int:id>', views.patient, name='patient'),
    path('addblog', views.addblog, name='addblog'),
    path('doctor/<int:id>/drafts', views.drafts, name='drafts'),
    path('doctor/<int:id>/blogs', views.blogs, name='blogs'),
    path('doctor/<int:id>/draft/<int:blogid>', views.update, name='update'),
    path('doctor/<int:id>/draft/<int:blogid>/updaterecord', views.updaterecord, name='updaterecord'),
    path('patient/<int:id>/viewblogs/<int:catid>', views.viewblogs, name='viewblogs'),
    path('patient/<int:id>/viewblogs/blog/<int:blogid>', views.viewblog, name='viewblog'),
    path('doctor/<int:id>/blog/<int:blogid>', views.docviewblog, name='viewblog'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/models.py
from pyexpat import model
from statistics import mode
from django.db import models

class User(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    type = models.CharField(max_length=10)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    confirm_password = models.CharField(max_length=30)
    line1 = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    pincode = models.CharField(max_length=30)
    profilepicture = models.ImageField(upload_to='images')  

class Blog(models.Model):
    title = models.CharField(max_length=255)
    summary = models.CharField(max_length=250)
    category = models.CharField(max_length=30)
    content = models.CharField(max_length=10000000)
    image = models.ImageField(upload_to='blogs')
    isdraft = models.IntegerField()
    user = models.CharField(max_length=20)

templates/blog.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/patient/{{ user.id }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/1">Mental Health</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/2">Heart Disease</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/3">Covid 19</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/4">Immunization</a>
            </li>
            <li>
                <a class="nav-link" href="/">Logout</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>

  <main id="main"></main>

    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">


          <div class="col-lg-12">
            <div class="portfolio-description">
              <img src="{{ blog.image.url}}" />
              <h2>{{ blog.title }}</h2>
              <br>
              <br>
              <p style="text-align: justify;">
                {{ blog.content }}
              </p>
            </div>
          </div>

        </div>

      </div>
    </section>

  </main><!-- End #main -->


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


  <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/blogs.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/doctor/{{ user.id }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/doctor/{{ user.id }}/drafts">Drafts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/doctor/{{ user.id }}/blogs">My Blogs</a>
          </li>
          <li>
            <a class="nav-link" href="/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <main id="main">


    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">
        {% for x in publishedblogs reversed%}
        {% if forloop.counter0|divisibleby:4 %}
        <div class="row">
          {% endif %}
          <div class="col-md-6 col-lg-3  align-items-stretch mb-5 mb-lg-0">
            <a href="blog/{{ x.id }}">
              <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                <img src="{{ x.image.url}}" />
                <h4 class="title">{{ x.title }}</h4>
                <p class="description">{{ x.summary|truncatewords:15 }}</p>
              </div>
            </a>
          </div>
          {% if forloop.counter != 0 %}
          {% if forloop.counter|divisibleby:4 %}
        </div>
        <br><br>
        {% endif %}
        {% endif %}
        {% endfor %}

      </div>
    </section><!-- End Services Section -->


  </main><!-- End #main -->



  <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/docblog.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/doctor/{{ user.id }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/doctor/{{ user.id }}/drafts">Drafts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/doctor/{{ user.id }}/blogs">My Blogs</a>
                </li>
                <li>
                    <a class="nav-link" href="/">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
  <main id="main"></main>

    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">


          <div class="col-lg-12">
            <div class="portfolio-description">
              <img src="{{ blog.image.url}}" />
              <h2>{{ blog.title }}</h2>
              <br>
              <br>
              <p style="text-align: justify;">
                {{ blog.content }}
              </p>
            </div>
          </div>

        </div>

      </div>
    </section>

  </main><!-- End #main -->


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


  <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/doctor.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<script>
    $(document).ready(function () {
        $("#newblog").hide();
        $("#new").click(function () {
            $("#newblog").show();
        });
        $("#cancel").click(function () {
            $("#newblog").hide();
        });
    });
</script>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/doctor/{{ user.id }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/doctor/{{ user.id }}/drafts">Drafts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/doctor/{{ user.id }}/blogs">My Blogs</a>
                    </li>
                    <li>
                        <a class="nav-link" href="/">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>Hi doctor {{ user.firstname }} {{ user.lastname }}</h1>
    <img src="{{ user.profilepicture.url}}" />
    
    <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/drafts.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<script>
  $(document).ready(function () {
    $("#newblog").hide();
    $("#new").click(function () {
      $("#newblog").toggle();
    });
    $("#cancel").click(function () {
      $("#newblog").hide();
    });
  });
</script>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link"  href="/doctor/{{ user.id }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/doctor/{{ user.id }}/drafts">Drafts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/doctor/{{ user.id }}/blogs">My Blogs</a>
          </li>
          <li>
            <a class="nav-link" href="/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <button id="new">Create New</button>
  <form id="newblog" method="post" action="/addblog" enctype="multipart/form-data">
    {% csrf_token %}
    {{ blogform.as_p }}
    <input type="hidden" value="{{ user.id }}" name="userid">
    <button id="cancel">Cancel</button>
    <button id="savedraft" name="savedraft" type="submit" value="True">Save as draft</button>
    <button id="upload" name="upload" type="submit" value="True">Upload</button>
  </form>

  <main id="main">


    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">
        {% for x in drafts reversed%}
        {% if forloop.counter0|divisibleby:4 %}
        <div class="row">
          {% endif %}
          <div class="col-md-6 col-lg-3  align-items-stretch mb-5 mb-lg-0">
            <a href="draft/{{ x.id }}">
              <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                <img src="{{ x.image.url}}" />
                <h4 class="title">{{ x.title }}</h4>
                <p class="description">{{ x.summary|truncatewords:15 }}</p>
              </div>
            </a>
          </div>
          {% if forloop.counter != 0 %}
          {% if forloop.counter|divisibleby:4 %}
        </div>
        <br><br>
        {% endif %}
        {% endif %}
        {% endfor %}

      </div>
    </section><!-- End Services Section -->


  </main><!-- End #main -->


  <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit">Upload</button>  
    </form>  
  
    {% if img_obj %}  
        <h3>Succesfully uploaded : {{img_obj.caption}}</h3>  
        <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">  
    {% endif %}  
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Login</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
  </head>

  <body>
    <div id="signupin" style="max-height:100vh">
      <form class="row g-3" method="post" action="login">
        {% csrf_token %}
        <div class="col-md-12">
          <input type="text" class="form-control" id="username" placeholder="User Name" name="username"/>
        </div>
        <div class="col-md-12">
          <input type="password" class="form-control" id="password" placeholder="Password" name="password"/>
        </div>
        <div class="col-md-12">
            <div>
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </div>
        <p>Dont have an account? <a href="signup">Sign Up</a></p>
        {% if error %}
        <p class="error">{{ error }}</p>
        {% endif %}
      </form>
    </div>

    <script src="{% static 'bootstrap.min.js' %}" async defer></script>
  </body>
</html>

templates/patient.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/patient/{{ user.id }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/1">Mental Health</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/2">Heart Disease</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/3">Covid 19</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/4">Immunization</a>
                    </li>
                    <li>
                        <a class="nav-link" href="/">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>Hi patient {{ user.firstname }} {{ user.lastname }}</h1>
    <img src="{{ user.profilepicture.url}}" />
    
    <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Sign Up</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
    <script>
        function passwordvalidate() {
            let password = document.getElementById("id_password").value;
            let confirmpassword = document.getElementById("id_confirm_password").value;
            if (password != confirmpassword) {
                document.getElementById("passworderror").innerHTML = "Passwords do not match";
                document.getElementById("submitbutton").disabled = true;
            }
            else{
                document.getElementById("passworderror").innerHTML = "";
                document.getElementById("submitbutton").disabled = false;
            }
        }
    </script>
</head>

<body>
    <div id="signupin">
        <form class="row g-3" method="post" enctype="multipart/form-data" action="signupdata" style="margin:100px 0px;">
            {% csrf_token %}
            <!--- <div class="col-md-6">
                <input type="text" class="form-control" id="inputCity" placeholder="First Name" />
            </div>
            <div class="col-md-6">
                <input type="text" class="form-control" id="inputState" placeholder="Last Name" />
            </div>
            <div class="col-md-6">
                <select id="type" name="Type">
                    <option value="Patient">Patient</option>
                    <option value="Doctor">Doctor</option>
                  </select>
            </div>-->

            {{ form.as_div }}

            <!--
            <div class="col-md-12">
                <input type="email" class="form-control" id="inputEmail4" placeholder="User Name" />
            </div>
            <div class="col-md-12">
                <input type="email" class="form-control" id="inputEmail4" onkeypress="emailvalidate()"
                    placeholder="Email" />
            </div>
            <div class="col-md-12">
                <input type="password" class="form-control" id="inputPassword4" placeholder="Password" />
            </div>
            <div class="col-md-12">
                <input type="password" class="form-control" id="inputPassword4" onkeypress="passwordvalidate()"
                    placeholder="Confirm Password" />
            </div>
            <div class="col-12">
                <input type="text" class="form-control" id="inputPhone" placeholder="Address"/>
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" id="inputCity" placeholder="City"/>
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" id="inputState" placeholder="State"/>
            </div>
            <div class="col-md-4">
                <input type="text" class="form-control" id="inputState" placeholder="Pincode"/>
            </div>
        -->
            <p id="passworderror"></p>
            <div class="col-12">
                <div>
                    <button type="submit" class="btn btn-primary" id="submitbutton">Sign Up</button>
                </div>
            </div>


            <p>Already have an account? <a href="login">Login</a></p>
        </form>
    </div>

    <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/update.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title></title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/doctor/{{ user.id }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/doctor/{{ user.id }}/drafts">Drafts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/doctor/{{ user.id }}/blogs">My Blogs</a>
          </li>
          <li>
            <a class="nav-link" href="/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <form method="post" action="{{ blog.id }}/updaterecord">
    {% csrf_token %}
    <p>
      <label for="id_title">Title:</label>
      <input type="text" name="title" maxlength="255" required="True" id="id_title" value="{{ blog.title }}" />
    </p>
    <p>
      <label for="id_summary">Summary:</label>
      <textarea name="summary" maxlength="250" required="True" id="id_summary" rows="3" cols="200">{{ blog.summary }}</textarea>
    </p>

    <p>
      <label for="id_content">Content:</label>
      <textarea name="content" maxlength="10000000" required="True" id="id_content" rows="10" cols="200">{{ blog.content }}</textarea>
    <button id="savedraft" name="savedraft" type="submit" value="True">
      Save as draft
    </button>
    <button id="upload" name="upload" type="submit" value="True">
      Upload
    </button>
  </form>

  <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>

templates/viewblogs.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'doctor.css' %}" type="text/css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/patient/{{ user.id }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/1">Mental Health</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/2">Heart Disease</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/3">Covid 19</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/patient/{{ user.id }}/viewblogs/4">Immunization</a>
            </li>
            <li>
                <a class="nav-link" href="/">Logout</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>

  <main id="main">
  

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">
        {% for x in blogs reversed%}
        {% if forloop.counter0|divisibleby:4 %}
        <div class="row">
          {% endif %}
          <div class="col-md-6 col-lg-3  align-items-stretch mb-5 mb-lg-0">
            <a href="blog/{{ x.id }}">
              <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                <img src="{{ x.image.url}}" />
                <h4 class="title">{{ x.title }}</h4>
                <p class="description">{{ x.summary|truncatewords:15 }}</p>
              </div>
            </a>
          </div>
          {% if forloop.counter != 0 %}
          {% if forloop.counter|divisibleby:4 %}
        </div>
        <br><br>
        {% endif %}
        {% endif %}
        {% endfor %}

      </div>
    </section><!-- End Services Section -->


  </main><!-- End #main -->



  <script src="{% static 'bootstrap.min.js' %}" async defer></script>
</body>

</html>